import jax.numpy as jnp

PENDING_SOURCE_KIND_NONE = jnp.int32(0)
PENDING_SOURCE_KIND_HOST = jnp.int32(1)
PENDING_SOURCE_KIND_SESSION_BINDING = jnp.int32(2)
PENDING_SOURCE_KIND_BOUND_NONE = jnp.int32(3)
