GLOBAL_MAX_HOSTS = 137
NUM_SUBNETS = 9
NUM_BLUE_AGENTS = 5
NUM_RED_AGENTS = 6
NUM_SERVICES = 5
NUM_DECOY_TYPES = 4
MISSION_PHASES = 3
MESSAGE_LENGTH = 8
MAX_STEPS = 500
TOTAL_ACTION_ACTOR_SLOTS = NUM_BLUE_AGENTS + GLOBAL_MAX_HOSTS + NUM_RED_AGENTS

SUBNET_NAMES = [
    "RESTRICTED_ZONE_A",
    "RESTRICTED_ZONE_B",
    "OPERATIONAL_ZONE_A",
    "OPERATIONAL_ZONE_B",
    "CONTRACTOR_NETWORK",
    "ADMIN_NETWORK",
    "OFFICE_NETWORK",
    "PUBLIC_ACCESS_ZONE",
    "INTERNET",
]

SUBNET_IDS = {name: i for i, name in enumerate(SUBNET_NAMES)}

CYBORG_SUBNET_SUFFIX = {
    "RESTRICTED_ZONE_A": "restricted_zone_a_subnet",
    "RESTRICTED_ZONE_B": "restricted_zone_b_subnet",
    "OPERATIONAL_ZONE_A": "operational_zone_a_subnet",
    "OPERATIONAL_ZONE_B": "operational_zone_b_subnet",
    "CONTRACTOR_NETWORK": "contractor_network_subnet",
    "ADMIN_NETWORK": "admin_network_subnet",
    "OFFICE_NETWORK": "office_network_subnet",
    "PUBLIC_ACCESS_ZONE": "public_access_zone_subnet",
    "INTERNET": "internet_subnet",
}

CYBORG_SUFFIX_TO_ID = {v: SUBNET_IDS[k] for k, v in CYBORG_SUBNET_SUFFIX.items()}

SERVICE_NAMES = ["SSHD", "APACHE2", "MYSQLD", "SMTP", "OTSERVICE"]
SERVICE_IDS = {name: i for i, name in enumerate(SERVICE_NAMES)}

DECOY_NAMES = ["HarakaSMPT", "Apache", "Tomcat", "Vsftpd"]
DECOY_IDS = {name: i for i, name in enumerate(DECOY_NAMES)}

COMPROMISE_NONE = 0
COMPROMISE_USER = 1
COMPROMISE_PRIVILEGED = 2

ACTIVITY_NONE = 0
ACTIVITY_SCAN = 1
ACTIVITY_EXPLOIT = 2

MAX_DETECTION_RANDOMS = 1024
NUM_GREEN_RANDOM_FIELDS = 8
NUM_RED_POLICY_RANDOM_FIELDS = 3

MIN_HOSTS_PER_SUBNET = 4
MAX_HOSTS_PER_SUBNET = 17

MAX_USER_HOSTS = 10
MAX_SERVER_HOSTS = 6
# Hosts per subnet in obs_host_map — includes router for action encoding.
OBS_HOSTS_PER_SUBNET = MAX_USER_HOSTS + MAX_SERVER_HOSTS + 1
# Hosts per subnet in the observation vector — excludes router (matches CybORG BlueFlatWrapper).
OBS_VECTOR_HOSTS_PER_SUBNET = MAX_USER_HOSTS + MAX_SERVER_HOSTS
ACTION_HOST_SLOTS = NUM_SUBNETS * OBS_HOSTS_PER_SUBNET
BLUE_MAX_OBSERVED_SUBNETS = 3
BLUE_ACTION_HOST_SLOTS = BLUE_MAX_OBSERVED_SUBNETS * OBS_VECTOR_HOSTS_PER_SUBNET
BLUE_TRAFFIC_SLOTS = (NUM_SUBNETS - 1) * BLUE_MAX_OBSERVED_SUBNETS
NUM_MESSAGES = NUM_BLUE_AGENTS - 1
# PID identity slots used for red session PID tracking.
# Peak observed: 33 with random blue over 50 seeds × 500 steps.
# 34 gives ~3% headroom over peak.
MAX_TRACKED_SESSION_PIDS = 34
# PID identity slots used for blue suspicious PID memory.
MAX_TRACKED_SUSPICIOUS_PIDS = 34
ABSTRACT_RANK_NONE = 1_000_000
BLUE_OBS_SIZE = (
    1
    + 3 * (NUM_SUBNETS + NUM_SUBNETS + NUM_SUBNETS + OBS_VECTOR_HOSTS_PER_SUBNET + OBS_VECTOR_HOSTS_PER_SUBNET)
    + NUM_MESSAGES * MESSAGE_LENGTH
)
